### ISSUE TITLE
Incompatible with new 64-bit game clients (STO)

### ISSUE THREAD

**Issue by bloggingninja** [gibbed/Gibbed.Cryptic#1]
Since Star Trek online updated to a 64 bit client awhile ago, this toolset doesn't appear to work with STO.

**Comment by Jff007** [comment]
Having same issues. Was hoping to develop client side model swapping for various ground weapons to remove those atrocious holograms on weapons. This and the extractor seem to no longer function.

**Comment by gibbed** [comment]
@Jff007 By extractor do you mean Unpack? because I haven't seen any issue with that on my end.

**Comment by Jff007** [comment]
Yeah, the unpacker worked for the first set of files I tried. But then I tried to unpack again, and nothing happened. I even redownloaded, used a different directory, and rebooted just to be sure.

**Comment by gibbed** [comment]
@Jff007 If you can figure out what's happening there, please open a new issue since that's separate from the 64-bit support.

**Comment by Jff007** [comment]
Noted, I'll try a couple of other Windows machines tomorrow to see if I can replicate it. If not, I'll edit this comment sometime before the next 24 hours.

Edit: Tested on 3 other Windows 10 machines. The unpack tool worked on one flawlessly, and on the other two intermittently. I'm willing to chalk up this issue to it just being a Windows config error.

**Comment by gibbed** [comment]
@Jff007 No worries, suggesting that since this issue will be closed momentarily.
